### ISSUE TITLE
add a color blast game

### ISSUE THREAD

**Issue by Arnabhit** [Aman1-coder/GameSphere#11] opened 2023-05-20 16:04 UTC
The above game is a Html,Css,JavaScript game that creates a canvas element and initializes various game
objects such as the player, enemies, bullets, and particles. It also handles user input for movement
and shooting, collision detection, and game over conditions. The game loop continuously updates and
renders the game objects on the canvas. The game can be paused and restarted by clicking on the
canvas or pressing the spacebar. Can you plz assign this issue to me.

**Comment by ayesha-firdaus** [comment] 2023-05-20 16:16
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by Aman1-coder** [comment] 2023-05-23 12:36
@Arnabhit @ayesha-firdaus It is a single player game please create new issue of multiplayer game

**Closed** 2023-05-23 12:36 UTC
Labels: GSSOC'23, On Hold
